### ISSUE TITLE
Offset for disk image

### ISSUE THREAD

**Issue by vpeter4** [oskarirauta/populatefs#4]
I'm evaluating populatefs to create disk image with two partitions. Because of this I extract ext4 partition from disk image, use populatefs on it and then merge back to disk image.
But I'm wondering if would be possible to add offset to populatefs to indicate where in disk image required partition starts. Similar to what mtools does (i'm using this also).

Regards, Peter

**Comment by oskarirauta** [comment]
populatefs used debugfs - therefore, if debugfs has this feature, this should be possible.

**Comment by vpeter4** [comment]
Seems even if populatefs would support offset in disk image I still need to format partition with one program (like mke2fs). And this kind of programs doesn't support this feature either. So extracting, manipulating and merging back is only option I see right now.

**Comment by oskarirauta** [comment]
You might be right. I haven’t been with this project in ages and currently I cannot help you as I am struggling with other issues in completely different language and world..

**Comment by vpeter4** [comment]
Just for fun I decided to make one shared library and hook open/close/seek/... system calls. Using LD_PRELOAD with mke2fs, tune2fs and e2fsck works as expected. I can use those programs directly on one big disk image to modify only part where partition reside.
